config/routes.rb
Rails.application.routes.draw do
 root 'posts#index'
  
  resources :posts do
    post 'comments', to: 'comments#create'
  end
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, allow_blank: false  
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :title#, :use => :slugged
    has_many :comments, dependent: :destroy
    
# paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy

  def username
    return email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
    @comments = @post.comments#page(params[:page]).per(4).order("created_at DESC")
  end

  def new
    @post = Post.new
    @comments = @post.comments
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
    [<%= comment.created_at.strftime("%I:%M %p")%>] <%= comment.user.username %>: <%= comment.body %>
    <br>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#exampleFormControlTextarea3').val('');

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
 <!--Footer-->
 <footer class="page-footer blue-gradient mt-0 pt-0 text-center text-md-left">

        <!--Footer Links-->
        <div class="container">

               <!--First row-->
               <div class="row">

                      <!--First column-->
                      <div class="col-md-12 py-4">

                             <div class="footer-socials mb-5 flex-center">

                                    <!--Facebook-->
                                    <a class="fb-ic">
                                           <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-lg"> </i>
                                    </a>
                                    <!--Twitter-->
                                    <a class="tw-ic">
                                           <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-lg"> </i>
                                    </a>
                                    <!--Google +-->
                                    <a class="gplus-ic">
                                           <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-lg">
                                           </i>
                                    </a>
                                    <!--Linkedin-->
                                    <a class="li-ic">
                                           <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-lg"> </i>
                                    </a>
                                    <!--Instagram-->
                                    <a class="ins-ic">
                                           <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-lg"> </i>
                                    </a>
                                    <!--Pinterest-->
                                    <a class="pin-ic">
                                           <i class="fab fa-pinterest fa-lg white-text fa-lg"> </i>
                                    </a>
                             </div>
                      </div>
                      <!--/First column-->
               </div>
               <!--/First row-->
        </div>
        <!--/Footer Links-->

        <!--Copyright-->
        <div class="footer-copyright text-center py-3">
               <div class="container-fluid">
                      © 2019 Copyright: <a href="www.generationsrs.com/" target="_blank">
                             Generationsrs </a>
               </div>
        </div>
        <!--/Copyright-->

 </footer>
 <!--/Footer-->

 <!-- SCRIPTS -->


 <script type="text/javascript">
        /* WOW.js init */
        new WOW().init();
 </script>

 <script>
        // Material Select Initialization
        $(document).ready(function () {
               $('.mdb-select').material_select();
        });
 </script>
 <script>
        // MDB Lightbox Init
        $(function () {
               $("#mdb-lightbox-ui").load("../../../mdb-addons/mdb-lightbox-ui.html");
        });
 </script>
 <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js"
        data-cf-settings="54fa5e813678873cb103f812-|49" defer=""></script>

app/views/layouts/_navigation.html.erb
  <!-- header
    ================================================== -->
    <header class="s-header">

        <div class="header-logo">
            <a class="site-logo" href="/">
                <%= image_tag   "", alt: "Nancy Logo" %>
            </a>
        </div> <!-- end header-logo -->

        <nav class="header-nav">

            <a href="#0" class="header-nav__close" title="close"><span>Close</span></a>

            <div class="header-nav__content">
                <h3>Generations Rehab Services</h3>
                
                <ul class="header-nav__list">
                    <li class="current"><a class="smoothscroll"  href="#home" title="home">Home</a></li>
                    <li><a class="smoothscroll"  href="#about" title="about">About</a></li>
                    <li><a class="smoothscroll"  href="#services" title="services">Services</a></li>
                    <li><a class="smoothscroll"  href="#works" title="works">Works</a></li>
                    <li><a class="smoothscroll"  href="#contact" title="contact">Contact</a></li>
                </ul>
    
                <p>Perspiciatis hic praesentium nesciunt. Et neque a dolorum <a href='#0'>voluptatem</a> porro iusto sequi veritatis libero enim. Iusto id suscipit veritatis neque reprehenderit.</p>
    
                <ul class="header-nav__social">
                    <li>
                        <a href="#0"><i class="fab fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-pinterest"></i></a>
                    </li>
                    <li>
                        <a href="#0"><i class="fab fa-dribbble"></i></a>
                    </li>
                </ul>

            </div> <!-- end header-nav__content -->

        </nav> <!-- end header-nav -->

        <a class="header-menu-toggle" href="#0">
            <span class="header-menu-icon"></span>
        </a>

    </header> <!-- end s-header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <title>Generations Rehab Services</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'track' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'false' %>
  
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%#= render 'layouts/footer' %>
    <script>
      AOS.init();
    </script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>